Improve code readability and speed
EIDOSLAB/torchstain pull request #41
Opened 2023-04-02 17:28 UTC by ajinkya-kulkarni

1. Used np.apply_along_axis to calculate stack_ instead of using a list comprehension.
2. Used elif statements instead of multiple if statements to improve code readability.

2023-04-04 13:02 UTC, andreped requested changes

2023-04-04 13:02 UTC, andreped commented on torchstain/numpy/normalizers/reinhard.py
> +        stack_ = np.apply_along_axis(get_mean_std, 1, lab_split(lab))
I would write `np.apply_along_axis(get_mean_std, axis=1, arr=lab_split(lab))`

2023-04-04 13:02 UTC, andreped commented on torchstain/numpy/normalizers/reinhard.py
> +        stack_ = np.apply_along_axis(get_mean_std, 1, labs)
Same as above.

2023-04-06 17:43 UTC, ajinkya-kulkarni commented
Done

2023-04-06 18:20 UTC, andreped commented
In order to merge, we need to run some unit tests. This is not possible, until you have replaced `ubuntu-18.04` with `ubuntu-20.04`, as mentioned [here](https://github.com/EIDOSLAB/torchstain/pull/39#issuecomment-1494159820) (necessary as `ubuntu-18.04` docker image is deprecated in GitHub Actions).

See [here](https://github.com/EIDOSLAB/torchstain/commit/8eed1bfc0257698da9b6f34cb9467ad9facc3866) for where to change. Alternatively, you can pull latest from the `main` branch to your own fork's branches.

2025-01-08 14:45 UTC, merged